# Generated by Django 3.2.9 on 2021-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211118_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Good'), (3, 'Fine'), (4, 'Amazing'), (5, 'Excellent')], null=True),
        ),
    ]
