# Generated by Django 3.2.9 on 2021-11-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Россия', 'Россия'), ('Турция', 'Турция'), ('Казахстан', 'Казахстан'), ('Белоруссия', 'Белоруссия'), ('Украина', 'Украина')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('message_to', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('house_type', models.CharField(choices=[('квартира', 'квартира'), ('дом', 'дом'), ('офис', 'офис'), ('гараж', 'гараж'), ('машиноместо', 'машиноместо')], max_length=20)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('sq_meters', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.person')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_house', to='store.person')),
            ],
        ),
    ]
