# Generated by Django 3.2.9 on 2021-11-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Book',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=255)),
        #         ('price', models.DecimalField(decimal_places=2, max_digits=7)),
        #     ],
        # ),
    ]
